[project]
name = "wisort"
version = "0.1.0"
description = "A system to sort your files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathspec>=0.12.1",
    "pydantic>=2.12.0",
    "typer>=0.19.2",
]
